spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?serverTimezone=UTC
      username: root
      password: 123456
      max-active: 40
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:MyBatisConfig.xml



pagehelper:
  helper-dialet: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql


sdk:
  alipay:
    dev: true
    sign-type: RSA2
    app-id: 2016100100642670
    private-key:  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCgyZ+ZV10rdSQsZ5EZpM4htctHYF9jPozB6Pndsasd26W7eexo9h7HQtHgw3tcWj0sMylr5KGz0G24d+JDeElzISXHbnDRg1vVW0LGGtzPzKc/ZpiadlJroajx0FqK3rr8Fg6ENgWQBp4/xJUecfkCPDUOW4NqCtCWlD/uG0LhBVi0Cbz+TzR7RdWAJm02elEz5juFitLRgW+TovgcoTxrzjW5QWEeuOzSVdk7F8MGPbx+vFKgDHc9jy6MeInTVspTsxxkWifD+Lz13fO2AgAt6pxKqFP7Xza99c/DshKr/hPYHIJZK9nUqOy6pspiBjYj8lRfzV1XFoAtt4epez3xAgMBAAECggEBAJBqiF9CiPyvin4Xx8wwqrS8hIjnlsWdOPAyQbtOCVQYJRPuvtjHt31iFwC6k+KvaqJ4kYvHHzZSzzoQ87mGIPK3oyctm0eTpLhN7/vfxNUgDFh13jtea0khOo13htuUkn45kXBO1VA3oYvFFeryk6XeTglHSRHGBPQ60/EZq0hQA1DOm3xh6m4Zhs47Zc+45OOy4FRpRQ4hjBG3vllNBDWheGStAbszsu9D4BOEsD0Njqkujpqb7PAviud+6P62nme7QOR3EqeNM16gm+QrmuN+EHVI1oHlUdGuIIoUZjbdNFIR8cO8l4CcoR7ckSSvlyfchwt84ARnFytYGIFn+cECgYEA8HaeA5shKBfdH/sebNrLQns8LnhYBFX1OYHWTTSETIrZwfdTlKwPJnd92tnhqXRD4DnHdpNNfp8BW0c1FrgCjpy42Lcz40sfuNfohRzUt0dVyPCM1Fl1rJCgTRPMcGIqzqLlnM4mF3PQGmf/ZVeO3/3ROfwmYhGPeicoBDisse8CgYEAqy0hNzehquagoiQ6611t1k2t//Aj39ixL4OxLnxY7es6iDBEDhmAltDl+6JAc5rA0fEM1Q0v8WZGl60KUaWp+TMS3BEbc3KEJUHYyYYl1+ZnOxZck/lT/MBvYtn5UzEbqKWQyFzTZq24Ldh5Zkm3BioUX7rS+m5Xp+/y7rKzbh8CgYB1HWCCYxi3/T9uZxD/dWSPwZOjEmvT2MWxt4HXYl+ZI/tA1CO6Aj7yvjnm0D1vGbhBSgLSxpV0uR6hBUJfCUn9iWkh68By0FDn5whRZKRZi33FexssBVIhtOLOB3mHttgggggQ4fp9a6OMaOBjzExC3cz8T8ml8+WMWevMeonpswKBgFhwZKzmrTxjE7MyDM714n3KfI+zPpW0mzb1T2G5FSk3U3JxnXe7bVh+bZRo6+vOlLjjVcHtokuSj/5lhONSOFNsM95HaGtpSyUEtEDKclrty4AXuZUqSF5Z/jKQc+SrhqLHh9o9O2vdbT8ijPZwN4OT0hrzp3WD9P3rVxREd7f5AoGBAJtP4pVmCSTf0CFyph4PQoP93brQFXznsnks8w+SVK/vb8wdAR+zjKFu22GlTcR8NYrKXc+/TJ+/dvtl0iBMXBs9xlifZGHbdKJ7UCdVW5NEwdefbOqKsm1v2GrOBFH7GlyDBfucZoaY63iEtFO9v3hULD/TlIZDlhekxRN/YLPb
    alipay-public-key:  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk1+4nzzqyi+i1TuNwpseCI6uosEFTK688cxfsZSpAyIZkFnXEXc0viC9RA1un4w7rg1mFshV+Zc+IPdxpX5O/brQSmRa6GSVDHifPRSVOPju4mE0rEVQX9Ilbc+Ktfx4Yed+CF3B6Wn/T+jcY664s44rPuCii5EKNiRhjptKAu+sTRvavL5z7Y+osVQV8LJDh8Ra7sENg7LmDzZQzkZj8XABKSqqasKm797YiuKisVuUp0e3GzBpE6Yzz0BtZo3NR1XR2iOn8Z8f6sTABHyZezSuV+KnyaymL9nt+fxoCA0gtU7gudlR+KfmNfTJct434pbFoeWtg8xRCdIkR0cr5QIDAQAB