package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import com.neuedu.pojoVO.CartProductVO;
import org.apache.ibatis.annotations.Param;
import org.springframework.web.bind.annotation.RequestMapping;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);

    List<CartProductVO> findCartDetailByUserid(@Param("userid")Integer userid);

    int findByUseridAndProductid(@Param("userid")int userid,
                                 @Param("productid") int productid);
    int updateByUseridAndProduct(@Param("userid")int userid,
                                 @Param("productid") int productid,
                                 @Param("count") int count);
    int deleteByUseridAndProductID(@Param("userid")int userid,
                                   @Param("productid") int productid);
    int checkedProduct(@Param("userid")int userid,
                       @Param("productid") int productid);
    int uncheckProduct(@Param("userid")int userid,
                       @Param("productid") int productid);
    List<Integer> getCartPCount(@Param("userid") int userid);

    int checkedAll(@Param("userid")int userid);

    int uncheckedAll(@Param("userid")int userid);
}