package com.neuedu.dao;

import com.neuedu.pojo.Order;
import com.neuedu.pojo.OrderItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Order record);

    List<OrderItem> findUserCheckedProduct(@Param("userid")int userid);

    Order findByOrderNo(@Param("orderNo") Long orderNo);

    List<OrderItem> findOrderItem(@Param("orderNo")Long orderNo);

    int findProductStock(@Param("productid")int productid);
    int findProductStatus(@Param("productid")int productid);

    List<Order> findOrderByUserid(@Param("userid")int userid);

    String findRecevierNameById(@Param("shippingId")int shippingId);

    Order findByOrderNoAndUserid(@Param("orderNo")Long orderNo,
                                 @Param("userId")int userId);

    List<Order> deleteOrderUnpaid();
}